# Generated by Django 3.2.12 on 2022-03-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_name_resource_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.ManyToManyField(blank=True, null=True, related_name='teachers', to='core.Subject'),
        ),
    ]
