# Generated by Django 3.2.12 on 2022-03-27 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_teacher_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='about',
            field=models.TextField(default=''),
        ),
    ]
